-- Flyway baseline 스키마. 2026-07-20 시점 전체 엔티티(16개 모듈)를 대상으로
-- jakarta.persistence.schema-generation.scripts.action=create 로 Hibernate가 직접 생성한 DDL을 그대로 채택했다
-- (수기 작성 시 오타·누락 위험을 피하기 위함 — enum CHECK 제약, FK, unique 제약, 인덱스까지 Hibernate가 실제로 만드는 것과 동일).
-- 이후 스키마 변경은 반드시 새 버전 마이그레이션(V2, V3, ...)으로 추가하고 이 파일은 수정하지 않는다.

    create table app_user (
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        email varchar(255) not null unique,
        name varchar(255) not null,
        password varchar(255) not null,
        phone varchar(255),
        primary key (id)
    );

    create table attendance_exception (
        target_date date not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        processed_by bigint,
        student_id bigint not null,
        tenant_id bigint not null,
        updated_at timestamp(6),
        reason varchar(255),
        status varchar(255) not null check ((status in ('PENDING','APPROVED','REJECTED'))),
        type varchar(255) not null check ((type in ('ABSENCE','LEAVE'))),
        primary key (id)
    );

    create table bus (
        insurance_expiry date,
        seat_capacity integer not null,
        created_at timestamp(6),
        driver_id bigint,
        id bigint generated by default as identity,
        route_id bigint,
        tenant_id bigint not null,
        updated_at timestamp(6),
        name varchar(255) not null,
        plate_number varchar(255),
        primary key (id)
    );

    create table drive_session (
        service_date date not null,
        bus_id bigint not null,
        created_at timestamp(6),
        driver_id bigint not null,
        ended_at timestamp(6),
        id bigint generated by default as identity,
        route_plan_id bigint,
        started_at timestamp(6) not null,
        tenant_id bigint not null,
        updated_at timestamp(6),
        direction varchar(255) not null check ((direction in ('PICKUP','DROPOFF'))),
        status varchar(255) not null check ((status in ('IN_PROGRESS','COMPLETED'))),
        primary key (id)
    );

    create table notification_log (
        created_at timestamp(6),
        id bigint generated by default as identity,
        student_id bigint not null,
        tenant_id bigint not null,
        updated_at timestamp(6),
        dedup_key varchar(255) not null unique,
        message varchar(255) not null,
        type varchar(255) not null check ((type in ('BOARD_DONE','ALIGHT_DONE','APPROACH','NO_SHOW','SOS','SCHEDULE_RESULT','CONNECTION_LOST','ROUTE_RECOMMENDED'))),
        primary key (id)
    );

    create table ride_event (
        lat float(53),
        lng float(53),
        bus_id bigint not null,
        corrected_at timestamp(6),
        corrected_by bigint,
        created_at timestamp(6),
        id bigint generated by default as identity,
        occurred_at timestamp(6) not null,
        original_ref bigint,
        stop_id bigint,
        student_id bigint not null,
        tenant_id bigint not null,
        updated_at timestamp(6),
        source varchar(255) not null check ((source in ('QR','NFC','MANUAL','CORRECTION'))),
        type varchar(255) not null check ((type in ('BOARD','ALIGHT'))),
        primary key (id)
    );

    create table route (
        assign_capacity integer not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        tenant_id bigint not null,
        updated_at timestamp(6),
        name varchar(255) not null,
        primary key (id)
    );

    create table route_plan (
        service_date date not null,
        total_distance_m float(53) not null,
        total_duration_s float(53) not null,
        version integer not null,
        approved_by bigint,
        bus_id bigint not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        published_by bigint,
        tenant_id bigint not null,
        updated_at timestamp(6),
        direction varchar(255) not null check ((direction in ('PICKUP','DROPOFF'))),
        polyline TEXT,
        status varchar(255) not null check ((status in ('DRAFT','RECOMMENDED','APPROVED','PUBLISHED'))),
        primary key (id)
    );

    create table route_plan_stop (
        lat float(53) not null,
        lng float(53) not null,
        seq integer not null,
        eta_seconds bigint not null,
        id bigint generated by default as identity,
        route_plan_id bigint not null,
        student_id bigint not null,
        primary key (id)
    );

    create table schedule_change_request (
        requested_date date not null,
        requested_time time(0) not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        processed_by bigint,
        student_id bigint not null,
        tenant_id bigint not null,
        updated_at timestamp(6),
        reason varchar(255),
        status varchar(255) not null check ((status in ('PENDING','APPROVED','REJECTED'))),
        primary key (id)
    );

    create table sos_event (
        lat float(53),
        lng float(53),
        acknowledged_at timestamp(6),
        acknowledged_by bigint,
        created_at timestamp(6),
        id bigint generated by default as identity,
        occurred_at timestamp(6) not null,
        resolved_at timestamp(6),
        resolved_by bigint,
        student_id bigint not null,
        tenant_id bigint not null,
        updated_at timestamp(6),
        status varchar(255) not null check ((status in ('OPEN','ACKNOWLEDGED','RESOLVED'))),
        primary key (id)
    );

    create table stop (
        lat float(53) not null,
        lng float(53) not null,
        seq integer not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        route_id bigint not null,
        updated_at timestamp(6),
        name varchar(255) not null,
        primary key (id)
    );

    create table student (
        dropoff_lat float(53),
        dropoff_lng float(53),
        bus_id bigint,
        created_at timestamp(6),
        id bigint generated by default as identity,
        stop_id bigint,
        tenant_id bigint not null,
        updated_at timestamp(6),
        user_id bigint,
        dropoff_address varchar(255),
        name varchar(255) not null,
        primary key (id)
    );

    create table student_guardian (
        created_at timestamp(6),
        guardian_id bigint not null,
        id bigint generated by default as identity,
        student_id bigint not null,
        updated_at timestamp(6),
        relation varchar(255),
        primary key (id),
        unique (student_id, guardian_id)
    );

    create table tenant (
        lat float(53),
        lng float(53),
        created_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        name varchar(255) not null,
        primary key (id)
    );

    create table user_tenant_role (
        created_at timestamp(6),
        id bigint generated by default as identity,
        tenant_id bigint,
        updated_at timestamp(6),
        user_id bigint not null,
        role varchar(255) not null check ((role in ('STUDENT','PARENT','DRIVER','ACADEMY_ADMIN','PLATFORM_ADMIN'))),
        primary key (id),
        unique (user_id, tenant_id, role)
    );

    create index idx_ride_tenant_student
       on ride_event (tenant_id, student_id, occurred_at);

    create index idx_sos_status_occurred
       on sos_event (status, occurred_at);

    alter table if exists bus
       add constraint FKfw4firf429suw6fjpetxotfvr
       foreign key (driver_id)
       references app_user;

    alter table if exists bus
       add constraint FKmrkjerbucw6j8sy8xewrig9wj
       foreign key (route_id)
       references route;

    alter table if exists bus
       add constraint FKjbkfidv283jnm0oswm34awxsp
       foreign key (tenant_id)
       references tenant;

    alter table if exists route
       add constraint FK5cxqeeubp2msjp9dtspd3dk19
       foreign key (tenant_id)
       references tenant;

    alter table if exists route_plan_stop
       add constraint FKhprjryk07m9o06d80682qtj0j
       foreign key (route_plan_id)
       references route_plan;

    alter table if exists stop
       add constraint FKdlo2jg2ydpg8cicshnqn7v4ex
       foreign key (route_id)
       references route;

    alter table if exists student
       add constraint FKpf87bmfntxa4waqd1mj7pp5fc
       foreign key (bus_id)
       references bus;

    alter table if exists student
       add constraint FKsxifhguqni1ck7htx240crep2
       foreign key (stop_id)
       references stop;

    alter table if exists student
       add constraint FKeti9162x7yovw7ukn83n7sue
       foreign key (tenant_id)
       references tenant;

    alter table if exists student_guardian
       add constraint FKl620cf1r3mminee0c58ll2ym3
       foreign key (guardian_id)
       references app_user;

    alter table if exists student_guardian
       add constraint FK3a2n27up9s1eotod8d63j3xyl
       foreign key (student_id)
       references student;

    alter table if exists user_tenant_role
       add constraint FKi37p8pvo0blr264j2v9x10b4g
       foreign key (tenant_id)
       references tenant;

    alter table if exists user_tenant_role
       add constraint FKgdt6pty2ea2knx9kb0u1a6ffa
       foreign key (user_id)
       references app_user;
